name: Build and deploy Frontend
on:
  push:
    branches:
    - main
    paths:
    - 'Frontend/**'
    - '.github/workflows/azure-staticwebapp.yml'
env:
  APP_DIRECTORY: Frontend
  OUTPUT: wwwroot
jobs:
  build_and_deploy_job: 
    name: Build and Deploy Job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true    
    - name: Build & Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: upload
        app_location: ${{ env.APP_DIRECTORY }}
        output_location: ${{ env.OUTPUT }}