name: Build and deploy Frontend to Netlify
on:
  push:
    branches:
    - main
    paths:
    - 'Frontend/**'
    - '.github/workflows/Netlify-Deploy.yml'
jobs:
  build:
    name: Build and Deploy Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true  
      - name: Setup .NET
        uses: actions/setup-dotnet@v3.1.0
        with:
          dotnet-version: 7.x.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: Frontend
      - name: Publish
        run: dotnet publish -c Release -o release
        working-directory: Frontend
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: Frontend/release/wwwroot
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

