name: Trigger auto deployment for selecionadouala
on:
  push:
    branches:
    - main
    paths:
    - 'Backend/**'
    - '.github/workflows/selecionadouala.yml'
  workflow_dispatch:      
jobs:
  build-and-deploy:
    name: Build and Deploy Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SELECIONADOUALA_AZURE_CREDENTIALS }}
      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/Backend 
          registryUrl: docker.io
          registryUsername: ${{ secrets.SELECIONADOUALA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SELECIONADOUALA_REGISTRY_PASSWORD }}
          containerAppName: selecionadouala
          resourceGroup: Default
          imageToBuild: kaaw/ualareplicaproject:latest
          dockerfilePath: Dockerfile
