name: Trigger auto deployment for selecionadouala

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - 'Backend/UalaReplicaProject/**'
    - '.github/workflows/selecionadouala.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SELECIONADOUALA_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/Backend/UalaReplicaProject 
          registryUrl: docker.io
          registryUsername: ${{ secrets.SELECIONADOUALA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SELECIONADOUALA_REGISTRY_PASSWORD }}
          containerAppName: selecionadouala
          resourceGroup: Default
          imageToBuild: kaaw/ualareplicaproject:latest
          dockerfilePath: Dockerfile
